DROP TABLE PERSONNEL;
DROP TABLE 
DROP TABLE 
DROP TABLE 
DROP TABLE 
DROP TABLE 





CREATE TABLE PERSONNEL
(
	ID				VARCHAR2(20) CONSTRAINT PK_PERSONNEL PRIMARY KEY,
	NOM				VARCHAR2(50),
	PRENOM			VARCHAR2(50),
	LOGIN			VARCHAR2(30),
	PASSWORD		VARCHAR2(30),
	MAILPRO			VARCHAR2(100),
	TELPRO			VARCHAR2(20),
	MAILPRIVE		VARCHAR2(100),
	TELPRIVE		VARCHAR2(20),
	AFFECTATION		VARCHAR2(20),
	FONCTION		VARCHAR2(30),
	BAREME			
	DATEENTREE		DATE,
	COMPTEBANCAIRE	VARCHAR2(30)
);


CREATE TABLE FACTURE
(
	ID_SOCIETE	
	-- Mois et année considérés
	TOTAL_HTVA	
	TOTAL_TVAC	
	FLAG_FACT_VALIDEE	NUMBER,
	ID_COMPTABLE		VARCHAR2(20),
	
);


CREATE TABLE ITEM_FACTURE
(
	ID_ITEM_FACTURE		VARCHAR2(20) CONSTRAINT PK_ITEM_FACTURE PRIMARY KEY,
	ID_FACTURE			VARCHAR2(20),
	ID_MOUVEMENT		VARCHAR2(20),
	ID_CONTAINER		VARCHAR2(20),
	DESTINATION			VARCHAR2(20),
	PRIX_HTVA			NUMBER
);


CREATE TABLE SALAIRE
(
);


CREATE TABLE PRIME
(
);


CREATE TABLE TARIF
(
	ID				NUMBER CONSTRAINT PK_TARIF PRIMARY KEY,
	TYPE		
	MATERIEL	
	PETROLIER	
	DATELASTUPDATE	DATE
);
