DROP TABLE ITEMS_FACTURE;
DROP TABLE SALAIRES;
DROP TABLE PRIMES;
DROP TABLE TARIFS;
DROP TABLE FACTURES;
DROP TABLE PERSONNEL;





CREATE TABLE PERSONNEL
(
	LOGIN				VARCHAR2(30) CONSTRAINT PK_PERSONNEL PRIMARY KEY,
	PASSWORD			VARCHAR2(30),
	NOM					VARCHAR2(50),
	PRENOM				VARCHAR2(50),
	MAILPRO				VARCHAR2(100),
	TELPRO				VARCHAR2(20),
	MAILPRIVE			VARCHAR2(100),
	TELPRIVE			VARCHAR2(20),
	AFFECTATION			VARCHAR2(20),
	FONCTION			VARCHAR2(30),
	BAREME				VARCHAR(30),
	DATEENTREESOCIETE	VARCHAR2(10),
	COMPTEBANCAIRE		VARCHAR2(30)
);


CREATE TABLE FACTURES
(
	ID_FACTURE			VARCHAR2(20) CONSTRAINT PK_FACTURES PRIMARY KEY,
	ID_SOCIETE			VARCHAR2(20),
	MOIS_ANNEE			VARCHAR2(7),
	TOTAL_HTVA			NUMBER,
	TOTAL_TVAC			NUMBER,
	FLAG_FACT_VALIDEE	NUMBER(1),
	LOGIN				VARCHAR2(30) CONSTRAINT REF_FACTURES_PERSONNEL REFERENCES PERSONNEL(LOGIN), -- Login (PK) du comptable
	FLAG_FACT_ENVOYEE	NUMBER(1),
	MOYEN_ENVOI			VARCHAR2(10),
	FLAG_FACT_PAYEE		NUMBER(1)
);


CREATE TABLE ITEMS_FACTURE
(
	ID_ITEM_FACTURE		VARCHAR2(20) CONSTRAINT PK_ITEMS_FACTURE PRIMARY KEY,
	ID_FACTURE			VARCHAR2(20) CONSTRAINT REF_ITEMS_FACTURE_FACTURES REFERENCES FACTURES(ID_FACTURE),
	ID_MOUVEMENT		VARCHAR2(20),
	ID_CONTAINER		VARCHAR2(20),
	DESTINATION			VARCHAR2(20),
	PRIX_HTVA			NUMBER
);


CREATE TABLE SALAIRES
(
	ID_SALAIRE			VARCHAR2(20) CONSTRAINT PK_SALAIRES PRIMARY KEY,
	LOGIN				VARCHAR2(30) CONSTRAINT REF_SALAIRES_PERSONNEL REFERENCES PERSONNEL(LOGIN),
	MOIS_ANNEE			VARCHAR2(7),
	MONTANT_BRUT		NUMBER,
	RETRAIT_ONNS		NUMBER,
	RETRAIT_PRECOMPTE	NUMBER,
	FLAG_FICHE_ENVOYEE	NUMBER(1),
	FLAG_SALAIRE_VERSE	NUMBER(1)
);


CREATE TABLE PRIMES
(
	ID_PRIME	VARCHAR2(20) CONSTRAINT PK_PRIMES PRIMARY KEY,
	MONTANT		NUMBER,
	DATE_OCTROI	VARCHAR2(10),
	MOTIF		VARCHAR2(100),
	LOGIN		VARCHAR2(30) CONSTRAINT REF_PRIMES_PERSONNEL REFERENCES PERSONNEL(LOGIN),
	FLAG_PAYEE	NUMBER(1)
);


CREATE TABLE TARIFS
(
	ID_TARIF			VARCHAR2(20) CONSTRAINT PK_TARIFS PRIMARY KEY,
	TARIF				NUMBER,
	TYPE				VARCHAR2(50),
	MATERIEL			VARCHAR2(50),
	FLAG_PETROLIER		NUMBER(1),
	DATE_DERNIERE_MAJ	VARCHAR2(10)
);

-- Principe des flags :
-- 0 = KO
-- 1 = Fait, contient