DROP TABLE CUSTOMERS;
DROP TABLE RESERVATIONS_PARC;
DROP TABLE PRODUITS;

CREATE TABLE CUSTOMERS
(
	LOGIN				VARCHAR2(30) CONSTRAINT PK_CUSTOMERS PRIMARY KEY,
	PASSWORD			VARCHAR2(30)
);

CREATE TABLE RESERVATIONS_PARC
(
	NBR_RESERVATIONS	NUMBER CONSTRAINT PK_RESERVATION PRIMARY KEY,
	DATE_RESERVATION	VARCHAR2(30)
);

CREATE TABLE PRODUITS
(
	ID_PRODUIT	NUMBER CONSTRAINT PK_PRODUITS PRIMARY KEY,
	NOM			VARCHAR2(30),
	DESCRIPTION	VARCHAR2(200),
	PRIX 		NUMBER,
	QUANTITE	NUMBER,
	RESERVE		NUMBER
);
