DROP TABLE CUSTOMERS;

CREATE TABLE CUSTOMERS
(
	LOGIN				VARCHAR2(30) CONSTRAINT PK_CUSTOMERS PRIMARY KEY,
	PASSWORD			VARCHAR2(30)
);

CREATE TABLE RESERVATIONS_PARC
(
	NBR_RESERVATIONS	NUMBER CONSTRAINT PK_RESERVATION PRIMARY KEY,
	DATE_RESERVATION	VARCHAR2(30)
);
