
CREATE USER TRAFIC IDENTIFIED BY TRAFIC DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER TRAFIC QUOTA UNLIMITED ON USERS;
GRANT ALTER SESSION TO TRAFIC;
GRANT CREATE DATABASE LINK TO TRAFIC;
GRANT CREATE SESSION TO TRAFIC;
GRANT CREATE PROCEDURE TO TRAFIC;
GRANT CREATE SEQUENCE TO TRAFIC;
GRANT CREATE TABLE TO TRAFIC;
GRANT CREATE TRIGGER TO TRAFIC;
GRANT CREATE TYPE TO TRAFIC;
GRANT CREATE SYNONYM TO TRAFIC;


