
DROP TABLE PARC;
DROP TABLE SOCIETE;
DROP TABLE CONTAINER;


CREATE TABLE SOCIETE
(
	ID_SOCIETE		VARCHAR2(20) CONSTRAINT PK_SOCIETE_ID PRIMARY KEY,
	CONTACT_NAME	VARCHAR2(20),
	MAIL			VARCHAR2(20),
	TELEPHONE		VARCHAR2(20),
	ADRESSE			VARCHAR2(50)
);

CREATE TABLE CONTAINER
(
	ID_CONTAINER	VARCHAR2(20) CONSTRAINT PK_CONTAINER_ID PRIMARY KEY,
	ID_SOCIETE		VARCHAR2(20) CONSTRAINT REF_SOCIETE_ID REFERENCES SOCIETE (ID_SOCIETE),
	CONTENU			VARCHAR2(20),
	DANGERS			VARCHAR2(20)
);


CREATE TABLE PARC
(
	X					NUMBER(3),
	Y					NUMBER(3),
	ID_CONTAINER		VARCHAR(20) CONSTRAINT REF_CONTAINER_ID REFERENCES CONTAINER (ID_CONTAINER),
	ETAT				NUMBER(1) CONSTRAINT CK_ETAT_VALUE CHECK (ETAT = 0 OR ETAT = 1 OR ETAT = 2),
	DATE_RESERVATION	DATE,
	DATE_ARRIVEE		DATE,
	POIDS				NUMBER(3),
	DESTINATION			VARCHAR2(20),
	TRANSPORT			VARCHAR2(6) CONSTRAINT CK_TRANSPORT_VALUE CHECK (TRANSPORT LIKE 'TRAIN' OR TRANSPORT LIKE 'BATEAU' OR TRANSPORT IS NULL),
	CONSTRAINT PK_PARC_X_Y  PRIMARY KEY (X, Y)
);

