-- BIDONNAGE DES DONNEES DE BASE


BEGIN

	-- INSERTION DES DESTINATIONS
	INSERT INTO DESTINATIONS (VILLE, DISTANCE_BATEAU, DISTANCE_TRAIN, DISTANCE_ROUTE) VALUES ('Seraing', 5, 10, 30);
	INSERT INTO DESTINATIONS (VILLE, DISTANCE_BATEAU, DISTANCE_TRAIN, DISTANCE_ROUTE) VALUES ('Verviers', 40, 25, 30);
	INSERT INTO DESTINATIONS (VILLE, DISTANCE_BATEAU, DISTANCE_TRAIN, DISTANCE_ROUTE) VALUES ('Herstal', 10, 5, 15);
	INSERT INTO DESTINATIONS (VILLE, DISTANCE_BATEAU, DISTANCE_TRAIN, DISTANCE_ROUTE) VALUES ('Visé', 15, 20, 25);
	INSERT INTO DESTINATIONS (VILLE, DISTANCE_BATEAU, DISTANCE_TRAIN, DISTANCE_ROUTE) VALUES ('Huy', 25, 30, 40);

	-- INSERTION DES EVALUATION
	INSERT INTO PARC (X, Y, ID_CONTAINER, ETAT, DATE_RESERVATION, DATE_ARRIVEE, POIDS, DESTINATION, TRANSPORT) VALUES (1, 1, NULL, 0, NULL, NULL, NULL, NULL, NULL);
	INSERT INTO PARC (X, Y, ID_CONTAINER, ETAT, DATE_RESERVATION, DATE_ARRIVEE, POIDS, DESTINATION, TRANSPORT) VALUES (2, 3, NULL, 0, NULL, NULL, NULL, NULL, NULL);
	INSERT INTO PARC (X, Y, ID_CONTAINER, ETAT, DATE_RESERVATION, DATE_ARRIVEE, POIDS, DESTINATION, TRANSPORT) VALUES (4, 4, NULL, 1, '11/10/2015', '15/09/2015', 1000, 'Seraing', 'BATEAU');
	INSERT INTO PARC (X, Y, ID_CONTAINER, ETAT, DATE_RESERVATION, DATE_ARRIVEE, POIDS, DESTINATION, TRANSPORT) VALUES (5, 6, NULL, 2, '5/10/2015', '9/10/2015', 2000, 'Verviers', 'TRAIN');
	INSERT INTO PARC (X, Y, ID_CONTAINER, ETAT, DATE_RESERVATION, DATE_ARRIVEE, POIDS, DESTINATION, TRANSPORT) VALUES (7, 7, NULL, 2, '8/10/2015', '10/10/2015', 3000, 'Seraing', 'TRAIN');

	COMMIT;
END;
/
