DROP TRIGGER SEQUENCESTATDESCR;
DROP TRIGGER SEQUENCETESTCONF;
DROP TRIGGER SEQUENCETESTHOMOG;
DROP TRIGGER SEQUENCETESTANOVA;





DROP SEQUENCE ID_RESULTATSSTATDESCR;
DROP SEQUENCE ID_RESULTATSTESTCONF;
DROP SEQUENCE ID_RESULTATSTESTHOMOG;
DROP SEQUENCE ID_RESULTATSTESTANOVA;





DROP TABLE RESULTATSSTATDESCR;
DROP TABLE RESULTATSTESTCONF;
DROP TABLE RESULTATSTESTHOMOG;
DROP TABLE RESULTATSTESTANOVA;





CREATE TABLE RESULTATSSTATDESCR
(
	ID				NUMBER CONSTRAINT PK_RESULTATSSTATDESCR PRIMARY KEY,
	MOYENNE			NUMBER,
	MODES			VARCHAR2(200), -- Car il peut y avoir plusieurs modes
	MEDIANE			NUMBER,
	ECARTTYPE		NUMBER,
	NBCONTAINERS	NUMBER,
	MOUVEMENT		VARCHAR2(3)
);


CREATE TABLE RESULTATSTESTCONF
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTCONF PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	RESULTAT		VARCHAR2(200)
);


CREATE TABLE RESULTATSTESTHOMOG
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTHOMOG PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	DESTINATIONA	VARCHAR2(30),
	DESTINATIONB	VARCHAR2(30),
	RESULTAT		VARCHAR2(200)
);


CREATE TABLE RESULTATSTESTANOVA
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTANOVA PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	RESULTAT		VARCHAR2(200)
);





CREATE SEQUENCE ID_RESULTATSSTATDESCR;
CREATE SEQUENCE ID_RESULTATSTESTCONF;
CREATE SEQUENCE ID_RESULTATSTESTHOMOG;
CREATE SEQUENCE ID_RESULTATSTESTANOVA;





CREATE OR REPLACE TRIGGER SEQUENCESTATDESCR
BEFORE INSERT ON RESULTATSSTATDESCR
FOR EACH ROW
BEGIN
	SELECT ID_RESULTATSSTATDESCR.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER SEQUENCETESTCONF
BEFORE INSERT ON RESULTATSTESTCONF
FOR EACH ROW
BEGIN
	SELECT ID_RESULTATSTESTCONF.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER SEQUENCETESTHOMOG
BEFORE INSERT ON RESULTATSTESTHOMOG
FOR EACH ROW
BEGIN
	SELECT ID_RESULTATSTESTHOMOG.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER SEQUENCETESTANOVA
BEFORE INSERT ON RESULTATSTESTANOVA
FOR EACH ROW
BEGIN
	SELECT ID_RESULTATSTESTANOVA.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
