DROP SEQUENCE ID_RESULTATSSTATDESCR;
DROP SEQUENCE ID_RESULTATSTESTCONF;
DROP SEQUENCE ID_RESULTATSTESTHOMOG;
DROP SEQUENCE ID_RESULTATSTESTANOVA;



DROP TABLE RESULTATSSTATDESCR;
DROP TABLE RESULTATSTESTCONF;
DROP TABLE RESULTATSTESTHOMOG;
DROP TABLE RESULTATSTESTANOVA;



CREATE TABLE RESULTATSSTATDESCR
(
	ID				NUMBER CONSTRAINT PK_RESULTATSSTATDESCR PRIMARY KEY,
	MOYENNE			NUMBER,
	MODES			VARCHAR2(100), -- Car il peut y avoir plusieurs modes
	MEDIANE			NUMBER,
	ECARTTYPE		NUMBER,
	NBCONTAINERS	NUMBER,
	MOUVEMENT		VARCHAR2(3)
);


CREATE TABLE RESULTATSTESTCONF
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTCONF PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	RESULTAT		VARCHAR2(100)
);


CREATE TABLE RESULTATSTESTHOMOG
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTHOMOG PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	DESTINATIONA	VARCHAR2(30),
	DESTINATIONB	VARCHAR2(30),
	RESULTAT		VARCHAR2(100)
);


CREATE TABLE RESULTATSTESTANOVA
(
	ID				NUMBER CONSTRAINT PK_RESULTATSTESTANOVA PRIMARY KEY,
	PVALUE			NUMBER,
	NBCONTAINERS	NUMBER,
	RESULTAT		VARCHAR2(100)
);



CREATE SEQUENCE ID_RESULTATSSTATDESCR;
CREATE SEQUENCE ID_RESULTATSTESTCONF;
CREATE SEQUENCE ID_RESULTATSTESTHOMOG;
CREATE SEQUENCE ID_RESULTATSTESTANOVA;
