/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application_trafic;

import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jerome
 */
public class Avec_reservation_panel extends javax.swing.JPanel {

    /**
     * Creates new form Avec_reservation_panel
     */
    public Avec_reservation_panel() {
        initComponents();
        idContainerList.setModel(new DefaultListModel());
        erreurLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        numReservationLabel = new javax.swing.JLabel();
        numeroTextField = new javax.swing.JTextField();
        idContainerLabel = new javax.swing.JLabel();
        idContainerTextField = new javax.swing.JTextField();
        ajouterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        idContainerList = new javax.swing.JList();
        retirerButton = new javax.swing.JButton();
        rechercheButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reponseList = new javax.swing.JList();
        reponseLabel = new javax.swing.JLabel();
        erreurLabel = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();

        titreLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titreLabel.setText("Entrée avec réservation");

        numReservationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numReservationLabel.setText("Numéro de réservation : ");

        idContainerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idContainerLabel.setText("ID container : ");

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(idContainerList);

        retirerButton.setText("retirer");
        retirerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerButtonActionPerformed(evt);
            }
        });

        rechercheButton.setText("Rechercher les emplacements");
        rechercheButton.setToolTipText("");
        rechercheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(reponseList);

        reponseLabel.setText("Réponse :");

        erreurLabel.setForeground(new java.awt.Color(255, 0, 0));
        erreurLabel.setText("jLabel1");

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idContainerLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(retirerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(idContainerTextField))
                                .addGap(18, 18, 18)
                                .addComponent(ajouterButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titreLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numReservationLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menuButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rechercheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reponseLabel)
                            .addComponent(erreurLabel))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titreLabel)
                    .addComponent(menuButton))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numReservationLabel)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idContainerLabel)
                    .addComponent(idContainerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retirerButton)
                .addGap(18, 18, 18)
                .addComponent(rechercheButton)
                .addGap(18, 18, 18)
                .addComponent(reponseLabel)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(erreurLabel)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        if(idContainerTextField.getText().isEmpty())
            return;
        
        ((DefaultListModel)idContainerList.getModel()).addElement(idContainerTextField.getText());                  
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void retirerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerButtonActionPerformed
        if(idContainerList.getSelectedIndex() < 0)
            return;
        
        ((DefaultListModel)idContainerList.getModel()).remove(idContainerList.getSelectedIndex()); 
    }//GEN-LAST:event_retirerButtonActionPerformed

    private void rechercheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheButtonActionPerformed
        erreurLabel.setVisible(false);
        
        if(numeroTextField.getText().isEmpty())
        {
            erreurLabel.setText("Vous devez préciser un numéros de réservation");
            erreurLabel.setVisible(true);
            return;
        }
        if(((DefaultListModel)idContainerList.getModel()).getSize() <= 0)
        {
            erreurLabel.setText("Vous devez préciser au moins un ID de container");
            erreurLabel.setVisible(true);
            return;
        }
        
        //TO DO envoi requete pour serveur
    }//GEN-LAST:event_rechercheButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        ((CardLayout)frame.getContentPane().getLayout()).show(frame.getContentPane(), "menu");
    }//GEN-LAST:event_menuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JLabel idContainerLabel;
    private javax.swing.JList idContainerList;
    private javax.swing.JTextField idContainerTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel numReservationLabel;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JButton rechercheButton;
    private javax.swing.JLabel reponseLabel;
    private javax.swing.JList reponseList;
    private javax.swing.JButton retirerButton;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
