/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application_trafic;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jerome
 */
public class Menu_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Panel
     */
    public Menu_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutButton = new javax.swing.JButton();
        titreLabel = new javax.swing.JLabel();
        entreeReservationButton = new javax.swing.JButton();
        sansReservation = new javax.swing.JButton();
        listOpButton = new javax.swing.JButton();

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        titreLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titreLabel.setText("Menu trafic");

        entreeReservationButton.setText("Camion avec réservation");
        entreeReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entreeReservationButtonActionPerformed(evt);
            }
        });

        sansReservation.setText("Camion sans réservation");
        sansReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sansReservationActionPerformed(evt);
            }
        });

        listOpButton.setText("Liste opération");
        listOpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreLabel)
                .addGap(265, 265, 265)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sansReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entreeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(354, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titreLabel))
                .addGap(36, 36, 36)
                .addComponent(entreeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sansReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(listOpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        
        frame.SendMsg("LOGOUT");
        
        CardLayout card = (CardLayout) frame.getContentPane().getLayout();
        card.show(frame.getContentPane(), "login");
        
        frame.logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void entreeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entreeReservationButtonActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        ((CardLayout)frame.getContentPane().getLayout()).show(frame.getContentPane(), "avecReservation");
    }//GEN-LAST:event_entreeReservationButtonActionPerformed

    private void sansReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sansReservationActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        ((CardLayout)frame.getContentPane().getLayout()).show(frame.getContentPane(), "sansReservation");
    }//GEN-LAST:event_sansReservationActionPerformed

    private void listOpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOpButtonActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        ((CardLayout)frame.getContentPane().getLayout()).show(frame.getContentPane(), "list");
    }//GEN-LAST:event_listOpButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entreeReservationButton;
    private javax.swing.JButton listOpButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton sansReservation;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables
}
