/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package application_trafic;

import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author John
 */
public class Sans_reservation_panel extends javax.swing.JPanel {

    /** Creates new form Sans_reservation_panel */
    public Sans_reservation_panel() {
        initComponents();
        idContainerList.setModel(new DefaultListModel());
        reponseList.setModel(new DefaultListModel());
        erreurLabel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titreLabel = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        idCamionLabel = new javax.swing.JLabel();
        immatriculationTextField = new javax.swing.JTextField();
        idContainerLabel = new javax.swing.JLabel();
        idContainerTextField = new javax.swing.JTextField();
        ajouterButton = new javax.swing.JButton();
        nothing = new javax.swing.JScrollPane();
        idContainerList = new javax.swing.JList();
        retirerButton = new javax.swing.JButton();
        rechercherButton = new javax.swing.JButton();
        reponseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reponseList = new javax.swing.JList();
        erreurLabel = new javax.swing.JLabel();

        titreLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titreLabel.setText("Sans réservations");

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        idCamionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idCamionLabel.setText("Immatriculation camion : ");

        idContainerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idContainerLabel.setText("ID container : ");

        ajouterButton.setText("Ajouter");
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });

        nothing.setViewportView(idContainerList);

        retirerButton.setText("Retirer");
        retirerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerButtonActionPerformed(evt);
            }
        });

        rechercherButton.setText("Rechercher");
        rechercherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherButtonActionPerformed(evt);
            }
        });

        reponseLabel.setText("Réponse : ");

        jScrollPane1.setViewportView(reponseList);

        erreurLabel.setForeground(new java.awt.Color(255, 0, 0));
        erreurLabel.setText("jLabel1");
        erreurLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titreLabel)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rechercherButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idContainerLabel)
                                    .addComponent(idCamionLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(immatriculationTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idContainerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ajouterButton)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(retirerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nothing, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(erreurLabel)
                                    .addComponent(reponseLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(198, 198, 198)
                .addComponent(menuButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreLabel)
                    .addComponent(menuButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCamionLabel)
                    .addComponent(immatriculationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idContainerLabel)
                    .addComponent(idContainerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajouterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nothing, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retirerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rechercherButton)
                .addGap(26, 26, 26)
                .addComponent(reponseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(erreurLabel)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        ((CardLayout)frame.getContentPane().getLayout()).show(frame.getContentPane(), "menu");
    }//GEN-LAST:event_menuButtonActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        if(idContainerTextField.getText().isEmpty())
            return;
        
        ((DefaultListModel)idContainerList.getModel()).addElement(idContainerTextField.getText());
        idContainerTextField.setText("");
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void retirerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerButtonActionPerformed
        if(idContainerList.getSelectedIndex() < 0)
            return;
        
        ((DefaultListModel)idContainerList.getModel()).remove(idContainerList.getSelectedIndex()); 
    }//GEN-LAST:event_retirerButtonActionPerformed

    private void rechercherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherButtonActionPerformed
        erreurLabel.setVisible(false);
        ((DefaultListModel)reponseList.getModel()).clear();
        
        if(immatriculationTextField.getText().isEmpty())
        {
            erreurLabel.setText("Vous devez préciser un numéro d'immatriculation");
            erreurLabel.setVisible(true);
            return;
        }
        if(((DefaultListModel)idContainerList.getModel()).getSize() <= 0)
        {
            erreurLabel.setText("Vous devez préciser au moins un ID de container");
            erreurLabel.setVisible(true);
            return;
        }
        
        GUI_Trafic frame = (GUI_Trafic)SwingUtilities.getWindowAncestor(this);
        
        String message = "INPUT_LORRY_WITHOUT_RESERVATION#" + immatriculationTextField.getText()+"#";
        
        for(int i = 0; i < ((DefaultListModel)idContainerList.getModel()).getSize(); i++)
        {
            message = message + ((DefaultListModel)idContainerList.getModel()).getElementAt(i)+"@";
        }
        
        frame.SendMsg(message);
        
        String[] reponse = frame.ReceiveMsg().split("#");
       
        if(reponse[0].equals("ERR"))
        {
            erreurLabel.setText(reponse[1]);
            erreurLabel.setVisible(true);
            return;
        }
        
        String[] emplacement = reponse[1].split("@");
        
        for(String s : emplacement)
        {
            ((DefaultListModel)reponseList.getModel()).addElement(s);
        }
    }//GEN-LAST:event_rechercherButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JLabel idCamionLabel;
    private javax.swing.JLabel idContainerLabel;
    private javax.swing.JList idContainerList;
    private javax.swing.JTextField idContainerTextField;
    private javax.swing.JTextField immatriculationTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuButton;
    private javax.swing.JScrollPane nothing;
    private javax.swing.JButton rechercherButton;
    private javax.swing.JLabel reponseLabel;
    private javax.swing.JList reponseList;
    private javax.swing.JButton retirerButton;
    private javax.swing.JLabel titreLabel;
    // End of variables declaration//GEN-END:variables

}
