/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application_trafic.recherchePanel;

import application_trafic.liste_Panel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author John
 */
public class date_panel extends javax.swing.JPanel {

    /**
     * Creates new form date_panel
     */
    public date_panel() {
        initComponents();
        erreurLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechercherButton = new javax.swing.JButton();
        debtuLabel = new javax.swing.JLabel();
        debtuLabel1 = new javax.swing.JLabel();
        erreurLabel = new javax.swing.JLabel();
        dateDebut = new javax.swing.JTextField();
        dateFin = new javax.swing.JTextField();

        rechercherButton.setText("Rechercher");
        rechercherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherButtonActionPerformed(evt);
            }
        });

        debtuLabel.setText("Date debut : ");

        debtuLabel1.setText("Date fin : ");

        erreurLabel.setForeground(new java.awt.Color(255, 0, 0));
        erreurLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(erreurLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rechercherButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(debtuLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(debtuLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debtuLabel)
                    .addComponent(debtuLabel1)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rechercherButton)
                    .addComponent(erreurLabel))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rechercherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherButtonActionPerformed
        erreurLabel.setVisible(false);
        
        if(dateDebut.getText().isEmpty())
        {
            erreurLabel.setVisible(true);
            erreurLabel.setText("Une date de début doit être indiquée ");
            return;
        }
        
        if(dateFin.getText().isEmpty())
        {
            erreurLabel.setVisible(true);
            erreurLabel.setText("Une date de fin doit être indiquée ");
            return;
        }
        
        liste_Panel parent = (liste_Panel)this.getParent().getParent();
        
        String m = "LIST_OPERATIONS#date#" + dateDebut.getText() + "#"+dateFin.getText();
        
        parent.recherche(m);
    }//GEN-LAST:event_rechercherButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateDebut;
    private javax.swing.JTextField dateFin;
    private javax.swing.JLabel debtuLabel;
    private javax.swing.JLabel debtuLabel1;
    private javax.swing.JLabel erreurLabel;
    private javax.swing.JButton rechercherButton;
    // End of variables declaration//GEN-END:variables
}
